# Generated by Django 6.0.2 on 2026-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecallparticipant',
            name='admitted',
            field=models.BooleanField(default=False),
        ),
    ]
