# Generated by Django 6.0.2 on 2026-09-20 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.CharField(db_index=True, max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('category_id', models.SlugField(help_text='Stable slug for grouping/ordering on the public page.', max_length=100)),
                ('category_order', models.PositiveIntegerField(default=0)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Display order within the category.')),
                ('question_en', models.TextField()),
                ('question_ar', models.TextField(blank=True)),
                ('short_answer_en', models.TextField()),
                ('short_answer_ar', models.TextField(blank=True)),
                ('detailed_answer_en', models.TextField(blank=True)),
                ('detailed_answer_ar', models.TextField(blank=True)),
                ('audience', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('AUTHENTICATED', 'Authenticated'), ('PARTNER', 'Partner'), ('INTERNAL', 'Internal')], default='INTERNAL', max_length=20)),
                ('content_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('BUSINESS_CONFIDENTIAL', 'Business Confidential'), ('PROPRIETARY', 'Proprietary'), ('HIGHLY_CONFIDENTIAL', 'Highly Confidential')], default='HIGHLY_CONFIDENTIAL', max_length=30)),
                ('sensitive_content', models.BooleanField(default=False)),
                ('ai_retrieval_allowed', models.BooleanField(default=False)),
                ('last_security_review', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Only one row per question_id may be current at a time - this is what every read query filters on.')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_entries', to='knowledge.knowledgeentry')),
            ],
            options={
                'verbose_name': 'Knowledge entry',
                'verbose_name_plural': 'Knowledge entries',
                'ordering': ['category_order', 'sequence', 'question_id'],
                'indexes': [models.Index(fields=['is_current', 'status', 'visibility'], name='knowledge_k_is_curr_3e9fcf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('question_id',), name='unique_current_knowledge_entry_per_question_id')],
            },
        ),
    ]
