# Generated by Django 6.0.2 on 2026-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_seed_master_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='category_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
