# Generated by Django 6.0.2 on 2026-07-20 10:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_public_ids'),
        ('evaluations', '0008_readiness_legal_record_db_guards'),
        ('interview_sessions', '0007_merge_20260709_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_number', models.CharField(db_index=True, max_length=80, unique=True)),
                ('report_version', models.CharField(default='week7-v1', max_length=40)),
                ('report_status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('STALE', 'Stale'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('readiness_status', models.CharField(blank=True, max_length=20)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('scoring_rule_set_name', models.CharField(blank=True, max_length=150)),
                ('scoring_rule_version', models.CharField(blank=True, max_length=40)),
                ('report_payload', models.JSONField(blank=True, default=dict)),
                ('competency_breakdown', models.JSONField(blank=True, default=list)),
                ('response_evidence_summary', models.JSONField(blank=True, default=list)),
                ('human_review_flags', models.JSONField(blank=True, default=list)),
                ('critical_failures', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_reports', to='candidates.candidate')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='evaluations.evaluation')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_evaluation_reports', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Evaluation Report',
                'verbose_name_plural': 'Evaluation Reports',
                'ordering': ['-generated_at', '-created_at'],
                'indexes': [models.Index(fields=['evaluation', 'generated_at'], name='reports_eva_evaluat_e54050_idx'), models.Index(fields=['session', 'generated_at'], name='reports_eva_session_bd8687_idx'), models.Index(fields=['candidate', 'generated_at'], name='reports_eva_candida_7457ef_idx'), models.Index(fields=['report_status', 'generated_at'], name='reports_eva_report__839796_idx')],
            },
        ),
    ]
