# Generated by Django 6.0.2 on 2026-07-21 06:28

import django.db.models.deletion
from django.db import migrations, models


def add_report_db_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    table_name = "reports_evaluationreport"

    if vendor == "sqlite":
        schema_editor.execute(
            f"""
            CREATE TRIGGER IF NOT EXISTS reports_evaluation_report_guard_update
            BEFORE UPDATE ON {table_name}
            WHEN NOT (
                OLD.report_status = 'GENERATED'
                AND NEW.report_status = 'STALE'
                AND OLD.id = NEW.id
                AND OLD.public_id = NEW.public_id
                AND OLD.created_at = NEW.created_at
                AND OLD.report_number = NEW.report_number
                AND OLD.report_version = NEW.report_version
                AND OLD.overall_score = NEW.overall_score
                AND OLD.max_score = NEW.max_score
                AND OLD.overall_percentage = NEW.overall_percentage
                AND OLD.readiness_status = NEW.readiness_status
                AND OLD.readiness_indicator = NEW.readiness_indicator
                AND OLD.readiness_reason = NEW.readiness_reason
                AND OLD.override_triggered = NEW.override_triggered
                AND OLD.rule_engine_version = NEW.rule_engine_version
                AND OLD.requires_human_review = NEW.requires_human_review
                AND OLD.scoring_rule_set_name = NEW.scoring_rule_set_name
                AND OLD.scoring_rule_version = NEW.scoring_rule_version
                AND OLD.report_payload = NEW.report_payload
                AND OLD.competency_breakdown = NEW.competency_breakdown
                AND OLD.response_evidence_summary = NEW.response_evidence_summary
                AND OLD.human_review_flags = NEW.human_review_flags
                AND OLD.critical_failures = NEW.critical_failures
                AND OLD.generated_at = NEW.generated_at
                AND OLD.metadata = NEW.metadata
                AND OLD.evaluation_id = NEW.evaluation_id
                AND OLD.session_id = NEW.session_id
                AND OLD.candidate_id = NEW.candidate_id
                AND (
                    OLD.readiness_legal_record_id = NEW.readiness_legal_record_id
                    OR (OLD.readiness_legal_record_id IS NULL AND NEW.readiness_legal_record_id IS NULL)
                )
                AND (
                    OLD.generated_by_id = NEW.generated_by_id
                    OR (OLD.generated_by_id IS NULL AND NEW.generated_by_id IS NULL)
                )
            )
            BEGIN
                SELECT RAISE(ABORT, 'Evaluation reports are immutable except for generated-to-stale versioning');
            END;
            """
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER IF NOT EXISTS reports_evaluation_report_guard_delete
            BEFORE DELETE ON {table_name}
            BEGIN
                SELECT RAISE(ABORT, 'Evaluation reports cannot be deleted');
            END;
            """
        )
        return

    if vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE OR REPLACE FUNCTION reports_prevent_report_mutation()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'Evaluation reports cannot be deleted';
                END IF;

                IF NOT (
                    OLD.report_status = 'GENERATED'
                    AND NEW.report_status = 'STALE'
                    AND OLD.id = NEW.id
                    AND OLD.public_id = NEW.public_id
                    AND OLD.created_at = NEW.created_at
                    AND OLD.report_number = NEW.report_number
                    AND OLD.report_version = NEW.report_version
                    AND OLD.overall_score = NEW.overall_score
                    AND OLD.max_score = NEW.max_score
                    AND OLD.overall_percentage = NEW.overall_percentage
                    AND OLD.readiness_status = NEW.readiness_status
                    AND OLD.readiness_indicator = NEW.readiness_indicator
                    AND OLD.readiness_reason = NEW.readiness_reason
                    AND OLD.override_triggered = NEW.override_triggered
                    AND OLD.rule_engine_version = NEW.rule_engine_version
                    AND OLD.requires_human_review = NEW.requires_human_review
                    AND OLD.scoring_rule_set_name = NEW.scoring_rule_set_name
                    AND OLD.scoring_rule_version = NEW.scoring_rule_version
                    AND OLD.report_payload IS NOT DISTINCT FROM NEW.report_payload
                    AND OLD.competency_breakdown IS NOT DISTINCT FROM NEW.competency_breakdown
                    AND OLD.response_evidence_summary IS NOT DISTINCT FROM NEW.response_evidence_summary
                    AND OLD.human_review_flags IS NOT DISTINCT FROM NEW.human_review_flags
                    AND OLD.critical_failures IS NOT DISTINCT FROM NEW.critical_failures
                    AND OLD.generated_at = NEW.generated_at
                    AND OLD.metadata IS NOT DISTINCT FROM NEW.metadata
                    AND OLD.evaluation_id = NEW.evaluation_id
                    AND OLD.session_id = NEW.session_id
                    AND OLD.candidate_id = NEW.candidate_id
                    AND OLD.readiness_legal_record_id IS NOT DISTINCT FROM NEW.readiness_legal_record_id
                    AND OLD.generated_by_id IS NOT DISTINCT FROM NEW.generated_by_id
                ) THEN
                    RAISE EXCEPTION 'Evaluation reports are immutable except for generated-to-stale versioning';
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        schema_editor.execute(
            f"""
            DROP TRIGGER IF EXISTS reports_evaluation_report_guard_update ON {table_name};
            CREATE TRIGGER reports_evaluation_report_guard_update
            BEFORE UPDATE ON {table_name}
            FOR EACH ROW
            EXECUTE FUNCTION reports_prevent_report_mutation();
            """
        )
        schema_editor.execute(
            f"""
            DROP TRIGGER IF EXISTS reports_evaluation_report_guard_delete ON {table_name};
            CREATE TRIGGER reports_evaluation_report_guard_delete
            BEFORE DELETE ON {table_name}
            FOR EACH ROW
            EXECUTE FUNCTION reports_prevent_report_mutation();
            """
        )


def remove_report_db_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    table_name = "reports_evaluationreport"

    if vendor == "sqlite":
        schema_editor.execute("DROP TRIGGER IF EXISTS reports_evaluation_report_guard_update;")
        schema_editor.execute("DROP TRIGGER IF EXISTS reports_evaluation_report_guard_delete;")
        return

    if vendor == "postgresql":
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS reports_evaluation_report_guard_update ON {table_name};"
        )
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS reports_evaluation_report_guard_delete ON {table_name};"
        )
        schema_editor.execute("DROP FUNCTION IF EXISTS reports_prevent_report_mutation();")


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_readiness_legal_record_db_guards'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreport',
            name='override_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationreport',
            name='readiness_indicator',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationreport',
            name='readiness_legal_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_reports', to='evaluations.evaluationreadinessdecisionrecord'),
        ),
        migrations.AddField(
            model_name='evaluationreport',
            name='readiness_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationreport',
            name='rule_engine_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(add_report_db_guards, remove_report_db_guards),
    ]
