# Generated by Django 6.0.2 on 2026-07-27 07:36

from django.db import migrations, models


def normalize_report_statuses(apps, schema_editor):
    EvaluationReport = apps.get_model("reports", "EvaluationReport")
    EvaluationReport.objects.filter(report_status="GENERATED").update(report_status="ACTIVE")
    EvaluationReport.objects.filter(report_status="STALE").update(report_status="SUPERSEDED")
    EvaluationReport.objects.filter(report_status="ARCHIVED").update(report_status="REVOKED")


def reverse_normalize_report_statuses(apps, schema_editor):
    EvaluationReport = apps.get_model("reports", "EvaluationReport")
    EvaluationReport.objects.filter(report_status="ACTIVE").update(report_status="GENERATED")
    EvaluationReport.objects.filter(report_status="SUPERSEDED").update(report_status="STALE")
    EvaluationReport.objects.filter(report_status="REVOKED").update(report_status="ARCHIVED")


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_evaluationreport_override_triggered_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_report_statuses, reverse_normalize_report_statuses),
        migrations.AlterField(
            model_name='evaluationreport',
            name='report_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('REVOKED', 'Revoked'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluationreport',
            name='report_version',
            field=models.CharField(default='1.2', max_length=40),
        ),
    ]
