# Generated by Django 6.0.2 on 2026-07-27 08:00

import api.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_db_immutability_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreport',
            name='employer_pdf',
            field=models.FileField(blank=True, null=True, upload_to=api.reports.models.report_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='evaluationreport',
            name='pdf_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
