# Generated by Django 6.0.2 on 2026-07-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_evaluationreport_employer_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationreport',
            name='report_version',
            field=models.CharField(default='1.3', max_length=40),
        ),
    ]
