# Generated by Django 6.0.2 on 2026-06-12 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('question_text', models.TextField()),
                ('expected_steps', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('language', models.CharField(default='EN', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Question Template',
                'verbose_name_plural': 'Question Templates',
                'ordering': ['role_name', 'domain', 'skill', 'created_at'],
                'indexes': [models.Index(fields=['role_name', 'language', 'is_active'], name='questions_q_role_na_01f870_idx'), models.Index(fields=['domain', 'skill'], name='questions_q_domain_5cb590_idx'), models.Index(fields=['difficulty'], name='questions_q_difficu_8990bd_idx')],
            },
        ),
    ]
