# Generated by Django 6.0.2 on 2026-06-17 06:59

from django.db import migrations, models


def populate_existing_skill_tags(apps, schema_editor):
    QuestionTemplate = apps.get_model("questions", "QuestionTemplate")
    for question in QuestionTemplate.objects.filter(skill_tag="").exclude(skill=""):
        question.skill_tag = question.skill
        question.save(update_fields=["skill_tag"])


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontemplate',
            options={'ordering': ['role_name', 'evaluation_tier', 'sequence_number', 'created_at'], 'verbose_name': 'Question Template', 'verbose_name_plural': 'Question Templates'},
        ),
        migrations.RemoveIndex(
            model_name='questiontemplate',
            name='questions_q_role_na_01f870_idx',
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='evaluation_tier',
            field=models.CharField(choices=[('FULL', 'Full Evaluation'), ('SCREENING', 'Screening')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question_set_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('SCENARIO', 'Scenario'), ('TASK', 'Task')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='role_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='rubric_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='scoring_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='skill_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='skill_tag',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['role_name', 'role_code', 'language', 'is_active'], name='questions_q_role_na_dec53e_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['skill_tag', 'evaluation_tier'], name='questions_q_skill_t_6f998a_idx'),
        ),
        migrations.RunPython(populate_existing_skill_tags, migrations.RunPython.noop),
    ]
