# Generated by Django 6.0.2 on 2026-06-18 12:06

from django.db import migrations, models


def backfill_v12_question_fields(apps, schema_editor):
    QuestionTemplate = apps.get_model("questions", "QuestionTemplate")

    semantic_map = {
        "SCENARIO": "scenario",
        "TASK": "scenario",
        "TEXT": "knowledge",
    }
    difficulty_scores = {
        "EASY": 1,
        "MEDIUM": 2,
        "HARD": 3,
    }

    for question in QuestionTemplate.objects.all():
        original_type = (question.question_type or "TEXT").upper()
        question.question_format = original_type
        question.question_type = semantic_map.get(original_type, "knowledge")
        question.question_status = "active" if question.is_active else "archived"
        question.question_version = question.question_version or "1.0"
        question.difficulty_score = difficulty_scores.get((question.difficulty or "MEDIUM").upper(), 2)
        question.estimated_time_seconds = 30 if original_type == "TEXT" else 60
        question.expected_answer_type = "structured"
        question.follow_up_allowed = False
        question.critical_question = False
        question.save(
            update_fields=[
                "question_format",
                "question_type",
                "question_status",
                "question_version",
                "difficulty_score",
                "estimated_time_seconds",
                "expected_answer_type",
                "follow_up_allowed",
                "critical_question",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questiontemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='critical_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='difficulty_score',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='estimated_time_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='expected_answer_type',
            field=models.CharField(choices=[('short', 'Short'), ('structured', 'Structured'), ('multi_step', 'Multi Step')], default='structured', max_length=20),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='follow_up_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question_format',
            field=models.CharField(choices=[('TEXT', 'Text'), ('SCENARIO', 'Scenario'), ('TASK', 'Task')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question_status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='evaluation_tier',
            field=models.CharField(choices=[('FULL', 'Full Evaluation'), ('SCREENING', 'Screening'), ('BOTH', 'Both')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='question_type',
            field=models.CharField(choices=[('safety', 'Safety'), ('integrity', 'Integrity'), ('behavioral', 'Behavioral'), ('communication', 'Communication'), ('situational', 'Situational'), ('scenario', 'Scenario'), ('knowledge', 'Knowledge')], default='knowledge', max_length=20),
        ),
        migrations.RunPython(backfill_v12_question_fields, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['role_code', 'question_code', 'language'], name='questions_q_role_co_ab6953_idx'),
        ),
    ]
