# Generated by Django 6.0.2 on 2026-10-08 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_normalize_question_skill_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_id', models.CharField(max_length=40, unique=True)),
                ('question_code', models.CharField(db_index=True, max_length=50)),
                ('bank_version', models.CharField(max_length=40)),
                ('indicator_type', models.CharField(choices=[('MUST_INCLUDE', 'Must Include'), ('NEGATIVE', 'Negative Indicator')], max_length=20)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('text_en', models.TextField(help_text='Locked English source text, exactly as in the approved bank.')),
                ('text_ar', models.TextField(blank=True)),
                ('text_ar_status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10)),
                ('text_ar_source', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(blank=True, help_text='S1/S2/S3 - empty until SME-assigned (D-04).', max_length=2)),
                ('mandatory', models.BooleanField(blank=True, help_text='Mandatory vs scored - null until SME-assigned (D-02).', null=True)),
            ],
            options={
                'ordering': ['question_code', 'indicator_type', 'ordinal'],
                'constraints': [models.UniqueConstraint(fields=('question_code', 'bank_version', 'indicator_type', 'ordinal'), name='unique_indicator_position_per_bank_version')],
            },
        ),
    ]
