from django.urls import path

from api.dashboard import views_admin
from . import views_b2b
from . import views_b2c

urlpatterns = [
    path('b2b/stats', views_b2b.B2BDashboardStatsView.as_view(), name='b2b-stats'),
    path('b2b/candidates/recent', views_b2b.B2BRecentCandidatesView.as_view(), name='b2b-recent-candidates'),
    path('b2b/evaluations/recent', views_b2b.B2BRecentEvaluationsView.as_view(), name='b2b-recent-evaluations'),
    path('b2b/score-distribution', views_b2b.B2BScoreDistributionView.as_view(), name='b2b-score-distribution'),
    path('b2b/evaluation-trend', views_b2b.B2BEvaluationTrendView.as_view(), name='b2b-evaluation-trend'),
    path('b2b/language-distribution', views_b2b.B2BLanguageDistributionView.as_view(), name='b2b-language-distribution'),
    path('b2b/performance-metrics', views_b2b.B2BPerformanceMetricsView.as_view(), name='b2b-performance-metrics'),
    path('b2b/status-distribution', views_b2b.B2BEvaluationStatusDistributionView.as_view(), name='b2b-status-distribution'),
    path('b2b/monthly-activity', views_b2b.B2BMonthlyActivityView.as_view(), name='b2b-monthly-activity'),
    path('b2b/candidate-comparison', views_b2b.B2BCandidateComparisonView.as_view(), name='b2b-candidate-comparison'),
    path('b2b/candidate-comparison/roles', views_b2b.B2BComparisonRolesView.as_view(), name='b2b-comparison-roles'),
    path('b2b/candidate-comparison/eligible-candidates', views_b2b.B2BComparisonEligibleCandidatesView.as_view(), name='b2b-comparison-eligible-candidates'),
    path('b2b/candidate-comparison/full', views_b2b.B2BComparisonFullView.as_view(), name='b2b-comparison-full'),
    path('b2b/candidate-comparison/pdf', views_b2b.B2BComparisonPdfView.as_view(), name='b2b-comparison-pdf'),
    path('b2b/job-role-distribution', views_b2b.B2BJobRoleDistributionView.as_view(), name='b2b-job-role-distribution'),
    path('b2b/evaluation-time-range', views_b2b.B2BEvaluationTimeRangeView.as_view(), name='b2b-evaluation-time-range'),
    path('b2b/dashboard-layout', views_b2b.B2BDashboardLayoutView.as_view(), name='b2b-dashboard-layout'),
    path('b2b/readiness-distribution', views_b2b.B2BReadinessDistributionView.as_view(), name='b2b-readiness-distribution'),
    path('b2b/requires-attention', views_b2b.B2BRequiresAttentionView.as_view(), name='b2b-requires-attention'),

    path('b2c/stats', views_b2c.B2CDashboardStatsView.as_view(), name='b2c-stats'),
    path('b2c/candidates/recent', views_b2c.B2CRecentCandidatesView.as_view(), name='b2c-recent-candidates'),
    path('b2c/evaluations/recent', views_b2c.B2CRecentEvaluationsView.as_view(), name='b2c-recent-evaluations'),
    path('b2c/candidate-comparison', views_b2c.B2CCandidateComparisonView.as_view(), name='b2c-candidate-comparison'),
    path('b2c/candidate-comparison/roles', views_b2c.B2CComparisonRolesView.as_view(), name='b2c-comparison-roles'),
    path('b2c/candidate-comparison/eligible-candidates', views_b2c.B2CComparisonEligibleCandidatesView.as_view(), name='b2c-comparison-eligible-candidates'),
    path('b2c/candidate-comparison/full', views_b2c.B2CComparisonFullView.as_view(), name='b2c-comparison-full'),
    path('b2c/candidate-comparison/pdf', views_b2c.B2CComparisonPdfView.as_view(), name='b2c-comparison-pdf'),
    path('b2c/evaluation-time-range', views_b2c.B2CEvaluationTimeRangeView.as_view(), name='b2c-evaluation-time-range'),
    path('b2c/status-distribution', views_b2c.B2CEvaluationStatusDistributionView.as_view(), name='b2c-status-distribution'),
    path('b2c/job-role-distribution', views_b2c.B2CJobRoleDistributionView.as_view(), name='b2c-job-role-distribution'),
    path('b2c/score-trend', views_b2c.B2CScoreTrendView.as_view(), name='b2c-score-trend'),
    path('b2c/language-distribution', views_b2c.B2CLanguageDistributionView.as_view(), name='b2c-language-distribution'),
    path('b2c/evaluation-trend', views_b2c.B2CEvaluationTrendView.as_view(), name='b2c-evaluation-trend'),
    path('b2c/monthly-activity', views_b2c.B2CMonthlyActivityView.as_view(), name='b2c-monthly-activity'),

    path('admin/stats', views_admin.AdminDashboardStatsView.as_view(), name='admin-stats'),
    path('admin/system-load', views_admin.AdminSystemLoadTrendView.as_view(), name='admin-system-load'),
    path('admin/user-growth', views_admin.AdminUserGrowthTrendView.as_view(), name='admin-user-growth'),
    path('admin/evaluation-types', views_admin.AdminEvaluationTypesDistributionView.as_view(), name='admin-evaluation-types'),
    path('admin/package-contribution', views_admin.AdminPackageContributionView.as_view(), name='admin-package-contribution'),
    path('admin/status-distribution', views_admin.AdminEvaluationStatusDistributionView.as_view(), name='admin-status-distribution'),
    path('admin/user-type-distribution', views_admin.AdminUserTypeDistributionView.as_view(), name='admin-user-type-distribution'),
    path('admin/revenue-trend', views_admin.AdminRevenueTrendView.as_view(), name='admin-revenue-trend'),
    path('admin/top-candidates', views_admin.AdminTopPerformingCandidatesView.as_view(), name='admin-top-candidates'),
    path('admin/recent-activity', views_admin.AdminRecentActivityView.as_view(), name='admin-recent-activity'),
    path('admin/geographic-distribution', views_admin.AdminGeographicDistributionView.as_view(), name='admin-geographic-distribution'),
    path('admin/candidate-comparison/accounts', views_admin.AdminComparisonAccountsView.as_view(), name='admin-comparison-accounts'),
    path('admin/candidate-comparison/roles', views_admin.AdminComparisonRolesView.as_view(), name='admin-comparison-roles'),
    path('admin/candidate-comparison/eligible-candidates', views_admin.AdminComparisonEligibleCandidatesView.as_view(), name='admin-comparison-eligible-candidates'),
    path('admin/candidate-comparison/full', views_admin.AdminComparisonFullView.as_view(), name='admin-comparison-full'),
    path('admin/candidate-comparison/pdf', views_admin.AdminComparisonPdfView.as_view(), name='admin-comparison-pdf'),
]
