# Generated by Django 6.0.2 on 2026-06-12 08:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('candidates', '0002_public_ids'),
        ('interviews', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('VERIFICATION_PENDING', 'Verification Pending'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=30)),
                ('role_name', models.CharField(max_length=100)),
                ('ui_language', models.CharField(default='EN', max_length=20)),
                ('candidate_language', models.CharField(default='EN', max_length=20)),
                ('tts_language_code', models.CharField(default='en-US', max_length=20)),
                ('stt_language_code', models.CharField(default='en-US', max_length=20)),
                ('translation_target', models.CharField(blank=True, max_length=20)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('identity_verified', models.BooleanField(default=False)),
                ('face_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('single_face_detected', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='candidates.candidate')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='interviews.interviewconfiguration')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_logs', to='candidates.candidate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_logs', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Integrity Log',
                'verbose_name_plural': 'Integrity Logs',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('skill', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('question_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASKED', 'Asked'), ('ANSWERED', 'Answered'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('asked_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_questions', to='questions.questiontemplate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Session Question',
                'verbose_name_plural': 'Session Questions',
                'ordering': ['question_order'],
            },
        ),
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_type', models.CharField(choices=[('TEXT', 'Text'), ('VOICE', 'Voice'), ('TASK', 'Task')], default='TEXT', max_length=20)),
                ('audio_url', models.URLField(blank=True)),
                ('text_response', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_sessions.interviewsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_sessions.sessionquestion')),
            ],
            options={
                'verbose_name': 'Candidate Response',
                'verbose_name_plural': 'Candidate Responses',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['candidate', 'status'], name='interview_s_candida_73ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['organization', 'status'], name='interview_s_organiz_3daf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['created_by', '-created_at'], name='interview_s_created_9aaa7b_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['expires_at'], name='interview_s_expires_ddf51a_idx'),
        ),
        migrations.AddIndex(
            model_name='integritylog',
            index=models.Index(fields=['session', '-detected_at'], name='interview_s_session_43899a_idx'),
        ),
        migrations.AddIndex(
            model_name='integritylog',
            index=models.Index(fields=['candidate', '-detected_at'], name='interview_s_candida_03b9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='integritylog',
            index=models.Index(fields=['event_type'], name='interview_s_event_t_a86989_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionquestion',
            index=models.Index(fields=['session', 'question_order'], name='interview_s_session_6df584_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionquestion',
            index=models.Index(fields=['session', 'status'], name='interview_s_session_52f929_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionquestion',
            unique_together={('session', 'question_order')},
        ),
        migrations.AddIndex(
            model_name='candidateresponse',
            index=models.Index(fields=['session', 'question'], name='interview_s_session_4ca44e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateresponse',
            index=models.Index(fields=['response_type'], name='interview_s_respons_15b51a_idx'),
        ),
    ]
