# Generated by Django 6.0.2 on 2026-06-24 08:10

import api.sessions.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0002_interviewsession_evaluation_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresponse',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=api.sessions.models.response_audio_upload_to),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='audio_file_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='audio_mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='audio_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='original_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_error_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_request_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='stt_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='transcript_language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionAudioArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=100)),
                ('voice_name', models.CharField(max_length=120)),
                ('language_code', models.CharField(max_length=20)),
                ('audio_file', models.FileField(upload_to=api.sessions.models.question_audio_upload_to)),
                ('audio_url', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('duration_estimate_seconds', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_artifacts', to='interview_sessions.sessionquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_audio_artifacts', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Question Audio Artifact',
                'verbose_name_plural': 'Question Audio Artifacts',
                'ordering': ['question__question_order', '-generated_at'],
                'indexes': [models.Index(fields=['session', 'question'], name='interview_s_session_cfdbf8_idx'), models.Index(fields=['provider', 'generated_at'], name='interview_s_provide_ff3e43_idx')],
                'unique_together': {('session', 'question', 'language_code', 'voice_name')},
            },
        ),
    ]
