# Generated by Django 6.0.2 on 2026-07-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0003_candidateresponse_audio_file_and_more'),
        ('interviews', '0004_packagesessionconfig_rolepackagecoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='certificate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='coverage_level',
            field=models.CharField(choices=[('SCREENING', 'Screening'), ('PARTIAL', 'Partial'), ('FULL', 'Full')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='package_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='package_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='package_session_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='interviews.packagesessionconfig'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='readiness_indicator_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='task_observation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
