# Generated by Django 6.0.2 on 2026-07-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('interview_sessions', '0004_interviewsession_certificate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_consent_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sessions', to='contracts.agreement'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='device_check_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='privacy_notice_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='privacy_notice_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='verbal_confirmation_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='verbal_confirmation_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
