# Generated by Django 6.0.2 on 2026-07-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0004_interviewsession_certificate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresponse',
            name='interpretation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='interpretation_status',
            field=models.CharField(default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='interpreted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='processing_status',
            field=models.CharField(default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translated_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translation_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translation_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translation_source_language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translation_status',
            field=models.CharField(default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='translation_target_language',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
