# Generated by Django 6.0.2 on 2026-07-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0005_candidateresponse_interpretation_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresponse',
            name='ai_processing_idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
