# Generated by Django 6.0.2 on 2026-07-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview_sessions", "0005_interviewsession_candidate_consent_agreement_and_more"),
        ("interview_sessions", "0006_candidateresponse_ai_processing_idempotency_key"),
    ]

    operations = []
