# Generated by Django 6.0.2 on 2026-07-23 07:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_public_ids'),
        ('interview_sessions', '0007_merge_20260709_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_code', models.CharField(max_length=100, unique=True)),
                ('task_name', models.CharField(max_length=150)),
                ('role_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('instruction_text', models.TextField(blank=True)),
                ('expected_steps', models.JSONField(blank=True, default=list)),
                ('max_duration_seconds', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Observed Task Definition',
                'verbose_name_plural': 'Observed Task Definitions',
                'ordering': ['role_code', 'task_name'],
                'indexes': [models.Index(fields=['role_code', 'is_active'], name='interview_s_role_co_abd423_idx'), models.Index(fields=['task_code'], name='interview_s_task_co_197173_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionObservedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REQUIRES_REVIEW', 'Requires Review')], default='READY', max_length=30)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_tasks', to='candidates.candidate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_tasks', to='interview_sessions.interviewsession')),
                ('task_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_tasks', to='interview_sessions.observedtaskdefinition')),
            ],
            options={
                'verbose_name': 'Session Observed Task',
                'verbose_name_plural': 'Session Observed Tasks',
                'ordering': ['task_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskObservationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('COMPLETED_WITH_REVIEW', 'Completed With Review'), ('INCOMPLETE', 'Incomplete'), ('FAILED', 'Failed')], default='INCOMPLETE', max_length=30)),
                ('task_completed', models.BooleanField(default=False)),
                ('sequence_correct', models.BooleanField(default=False)),
                ('execution_time_seconds', models.PositiveIntegerField(default=0)),
                ('review_required', models.BooleanField(default=False)),
                ('review_reason', models.TextField(blank=True)),
                ('observed_steps', models.JSONField(blank=True, default=list)),
                ('missing_steps', models.JSONField(blank=True, default=list)),
                ('integrity_flags', models.JSONField(blank=True, default=list)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_observation_results', to='candidates.candidate')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_task_observation_results', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_observation_results', to='interview_sessions.interviewsession')),
                ('session_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='interview_sessions.sessionobservedtask')),
            ],
            options={
                'verbose_name': 'Task Observation Result',
                'verbose_name_plural': 'Task Observation Results',
                'ordering': ['session_task__task_order', '-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionobservedtask',
            index=models.Index(fields=['session', 'status'], name='interview_s_session_de2eff_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionobservedtask',
            index=models.Index(fields=['candidate', 'status'], name='interview_s_candida_7266d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionobservedtask',
            unique_together={('session', 'task_definition'), ('session', 'task_order')},
        ),
        migrations.AddIndex(
            model_name='taskobservationresult',
            index=models.Index(fields=['session', 'generated_at'], name='interview_s_session_c3f5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='taskobservationresult',
            index=models.Index(fields=['candidate', 'generated_at'], name='interview_s_candida_cf642f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskobservationresult',
            index=models.Index(fields=['status'], name='interview_s_status_f1cac3_idx'),
        ),
    ]
