# Generated by Django 6.0.2 on 2026-07-27 06:09

import api.sessions.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_public_ids'),
        ('interview_sessions', '0008_observedtaskdefinition_sessionobservedtask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=api.sessions.models.session_artifact_upload_to)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_artifacts', to='candidates.candidate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='interview_sessions.interviewsession')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_session_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Artifact',
                'verbose_name_plural': 'Session Artifacts',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['session', 'artifact_type'], name='interview_s_session_badb1b_idx'), models.Index(fields=['candidate', 'artifact_type'], name='interview_s_candida_b9812e_idx'), models.Index(fields=['uploaded_at'], name='interview_s_uploade_71b7ec_idx')],
            },
        ),
    ]
