# Generated by Django 6.0.2 on 2026-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0009_sessionartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='integrity_violation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
