# Generated by Django 6.0.2 on 2026-08-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0011_interviewsession_scheduling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='access_password_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='access_password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
