# Generated by Django 6.0.2 on 2026-06-04 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('B2B', 'B2B Company'), ('B2C', 'B2C Individual'), ('B2B_TEAM_MEMBER', 'B2B Team Member')], default='B2C', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password_reset_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('documents_verified', models.BooleanField(default=False)),
                ('documents_verified_at', models.DateTimeField(blank=True, null=True)),
                ('documents_verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_permissions', models.JSONField(blank=True, default=list)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_team_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('company_size', models.CharField(max_length=10)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('registration_certificate', models.FileField(upload_to='companies/certificates/')),
                ('tax_id_document', models.FileField(blank=True, null=True, upload_to='companies/tax/')),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_company', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.company'),
        ),
        migrations.CreateModel(
            name='CompanyEmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_registration_number', models.CharField(max_length=100, unique=True)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], max_length=10)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('AR', 'Arabic'), ('DE', 'German'), ('ZH', 'Chinese')], default='EN', max_length=2)),
                ('registration_certificate', models.FileField(upload_to='b2b/documents/registration/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('resachetified_license', models.FileField(upload_to='b2b/documents/license/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('tax_id_document', models.FileField(blank=True, null=True, upload_to='b2b/documents/tax/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='b2b/documents/additional/')),
                ('documents_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to='accounts.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Employer Profile',
                'verbose_name_plural': 'Company Employer Profiles',
            },
        ),
        migrations.CreateModel(
            name='IndividualEmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('passport_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('job_role', models.CharField(choices=[('SE', 'Software Engineer'), ('DS', 'Data Scientist'), ('PM', 'Product Manager'), ('MK', 'Marketing'), ('SL', 'Sales'), ('HR', 'Human Resources'), ('FN', 'Finance'), ('OT', 'Other')], max_length=2)),
                ('nationality', models.CharField(choices=[('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('AE', 'UAE'), ('SA', 'Saudi Arabia'), ('EG', 'Egypt'), ('IN', 'India'), ('CN', 'China'), ('JP', 'Japan'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('OT', 'Other')], max_length=2)),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('AR', 'Arabic'), ('DE', 'German'), ('ZH', 'Chinese')], default='EN', max_length=2)),
                ('id_document', models.FileField(upload_to='b2c/documents/id/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('resume_document', models.FileField(upload_to='b2c/documents/resume/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='b2c/documents/additional/')),
                ('documents_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual Employer Profile',
                'verbose_name_plural': 'Individual Employer Profiles',
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=100)),
                ('permissions', models.JSONField(default=list)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.company')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Invitation',
                'verbose_name_plural': 'Team Invitations',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('permissions', models.JSONField(default=list)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='accounts.company')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member Profile',
                'verbose_name_plural': 'Team Member Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['registration_number'], name='accounts_co_registr_7de6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='accounts_co_name_a6c199_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['token'], name='accounts_te_token_8d263f_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['email', 'status'], name='accounts_te_email_8d3b85_idx'),
        ),
    ]
