# Generated by Django 6.0.2 on 2026-06-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_public_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('B2B', 'B2B Company'), ('B2C', 'B2C Individual'), ('B2B_TEAM_MEMBER', 'B2B Team Member'), ('CANDIDATE', 'Candidate')], default='B2C', max_length=15),
        ),
    ]
