# Generated by Django 6.0.2 on 2026-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stamp_image',
            field=models.ImageField(blank=True, help_text='Company stamp/seal, applied automatically to signed B2B agreement PDFs.', null=True, upload_to='companies/stamps/'),
        ),
    ]
