# Generated by Django 6.0.2 on 2026-07-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_stamp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('AM', 'Amharic'), ('OM', 'Afaan Oromo'), ('FIL', 'Filipino'), ('ZH', 'Chinese')], default='EN', max_length=3),
        ),
        migrations.AlterField(
            model_name='individualemployerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('AM', 'Amharic'), ('OM', 'Afaan Oromo'), ('FIL', 'Filipino'), ('ZH', 'Chinese')], default='EN', max_length=3),
        ),
    ]
