# Generated by Django 6.0.2 on 2026-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_companyemployerprofile_preferred_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('AM', 'Amharic'), ('OM', 'Afaan Oromo'), ('FIL', 'Filipino'), ('ZH', 'Chinese'), ('HI', 'Hindi'), ('UR', 'Urdu'), ('BN', 'Bengali'), ('TA', 'Tamil'), ('TE', 'Telugu'), ('ML', 'Malayalam'), ('PA', 'Punjabi'), ('SI', 'Sinhala'), ('ID', 'Indonesian'), ('NE', 'Nepali'), ('SW', 'Swahili'), ('VI', 'Vietnamese'), ('KM', 'Khmer'), ('MY', 'Burmese'), ('TI', 'Tigrinya'), ('SO', 'Somali'), ('AA', 'Afar'), ('AK', 'Twi (Akan)'), ('LG', 'Luganda'), ('MG', 'Malagasy')], default='EN', max_length=3),
        ),
        migrations.AlterField(
            model_name='individualemployerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('AM', 'Amharic'), ('OM', 'Afaan Oromo'), ('FIL', 'Filipino'), ('ZH', 'Chinese'), ('HI', 'Hindi'), ('UR', 'Urdu'), ('BN', 'Bengali'), ('TA', 'Tamil'), ('TE', 'Telugu'), ('ML', 'Malayalam'), ('PA', 'Punjabi'), ('SI', 'Sinhala'), ('ID', 'Indonesian'), ('NE', 'Nepali'), ('SW', 'Swahili'), ('VI', 'Vietnamese'), ('KM', 'Khmer'), ('MY', 'Burmese'), ('TI', 'Tigrinya'), ('SO', 'Somali'), ('AA', 'Afar'), ('AK', 'Twi (Akan)'), ('LG', 'Luganda'), ('MG', 'Malagasy')], default='EN', max_length=3),
        ),
    ]
