# Generated by Django 6.0.2 on 2026-08-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text="Free-text self-described business roles/categories (e.g. 'Agency', 'Staffing') shown as badges on the Company Profile page. Not related to Candidate.job_role or the interview role_code taxonomy."),
        ),
    ]
