# Generated by Django 6.0.2 on 2026-08-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Set whenever the password is changed or reset. Access tokens issued before this are rejected.', null=True),
        ),
    ]
