# Generated by Django 6.0.2 on 2026-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployerprofile',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('both', 'Both')], default='email', max_length=10),
        ),
    ]
