# Generated by Django 6.0.2 on 2026-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_companyemployerprofile_target_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyemployerprofile',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
