# Generated by Django 6.0.2 on 2026-09-23 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualemployerprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='b2c/documents/id/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='individualemployerprofile',
            name='resume_document',
            field=models.FileField(blank=True, null=True, upload_to='b2c/documents/resume/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
