# Generated by Django 6.0.2 on 2026-10-03 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_companydocumentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployerprofile',
            name='resachetified_license',
            field=models.FileField(blank=True, null=True, upload_to='b2b/documents/license/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
