# Generated by Django 6.0.2 on 2026-10-07 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_reset_inferred_business_license_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='companies/certificates/'),
        ),
        migrations.AlterField(
            model_name='companyemployerprofile',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='b2b/documents/registration/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
