# Generated by Django 6.0.2 on 2026-10-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_company_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dashboard_layout',
            field=models.JSONField(blank=True, default=dict, help_text="Company-wide B2B overview dashboard customization: {'widgets': [ordered visible widget ids]}. Empty means the default layout (see api/dashboard/dashboard_layout.py)."),
        ),
    ]
