# Generated by Django 6.0.2 on 2026-06-04 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('candidates', '0001_initial'),
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_job_roles', models.CharField(help_text='Comma-separated job role codes this category applies to', max_length=255)),
            ],
            options={
                'verbose_name': 'Score Category',
                'verbose_name_plural': 'Score Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('area', models.CharField(choices=[('COMMUNICATION', 'Communication'), ('RELIABILITY', 'Reliability'), ('PUNCTUALITY', 'Punctuality'), ('PROFESSIONALISM', 'Professionalism'), ('TEAMWORK', 'Teamwork'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance'), ('ORGANIZATION', 'Organization'), ('ATTENTION_TO_DETAIL', 'Attention to Detail'), ('COMPANIONSHIP', 'Companionship'), ('PATIENCE', 'Patience'), ('MEDICATION_MANAGEMENT', 'Medication Management'), ('FIRST_AID', 'First Aid'), ('ELDERLY_CARE', 'Elderly Care'), ('CHILD_CARE', 'Child Care'), ('SAFE_DRIVING', 'Safe Driving'), ('ROUTE_PLANNING', 'Route Planning'), ('VEHICLE_MAINTENANCE', 'Vehicle Maintenance'), ('NAVIGATION', 'Navigation'), ('FOOD_PREPARATION', 'Food Preparation'), ('KITCHEN_HYGIENE', 'Kitchen Hygiene'), ('MENU_PLANNING', 'Menu Planning'), ('BUDGETING', 'Budgeting'), ('DIETARY_KNOWLEDGE', 'Dietary Knowledge')], max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this score')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='candidates.candidate')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scores', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(blank=True, help_text='The evaluation this score is associated with (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Candidate Score',
                'verbose_name_plural': 'Candidate Scores',
                'ordering': ['candidate', 'area'],
                'indexes': [models.Index(fields=['candidate'], name='scores_cand_candida_0abc4e_idx'), models.Index(fields=['evaluation'], name='scores_cand_evaluat_ff5be3_idx'), models.Index(fields=['area'], name='scores_cand_area_cf5ac3_idx'), models.Index(fields=['created_by'], name='scores_cand_created_67ff32_idx')],
                'unique_together': {('candidate', 'evaluation', 'area')},
            },
        ),
        migrations.CreateModel(
            name='ScoreSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sets', to='candidates.candidate')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_sets', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_score_sets', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_set', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Score Set',
                'verbose_name_plural': 'Score Sets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate'], name='scores_scor_candida_3aeaec_idx'), models.Index(fields=['evaluation'], name='scores_scor_evaluat_350812_idx')],
            },
        ),
    ]
