# Generated by Django 6.0.2 on 2026-06-04 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('evaluation_type', models.CharField(choices=[('INTERVIEW', 'Interview'), ('TECHNICAL_TEST', 'Technical Test'), ('ASSESSMENT', 'Assessment'), ('LANGUAGE_PROFICIENCY', 'Language Proficiency')], help_text='Type of evaluation (interview, technical test, etc.)', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', help_text='Current status of the evaluation', max_length=20)),
                ('scheduled_date', models.DateTimeField(help_text='Date and time when the evaluation is scheduled')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of the evaluation in minutes', validators=[django.core.validators.MinValueValidator(15)])),
                ('candidate_first_name', models.CharField(max_length=150)),
                ('candidate_last_name', models.CharField(max_length=150)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_passport_id', models.CharField(max_length=50)),
                ('candidate_job_role', models.CharField(choices=[('SE', 'Software Engineer'), ('DS', 'Data Scientist'), ('PM', 'Product Manager'), ('MK', 'Marketing'), ('SL', 'Sales'), ('HR', 'Human Resources'), ('FN', 'Finance'), ('OT', 'Other')], max_length=2)),
                ('candidate_preferred_language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('AR', 'Arabic'), ('DE', 'German'), ('ZH', 'Chinese')], default='EN', max_length=2)),
                ('certificate_status', models.CharField(choices=[('NOT_ISSUED', 'Not Issued'), ('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('EXPIRED', 'Expired')], default='NOT_ISSUED', help_text='Status of any certificate for this evaluation', max_length=20)),
                ('certificate_issued_at', models.DateTimeField(blank=True, help_text='When the certificate was issued (if applicable)', null=True)),
                ('certificate_url', models.URLField(blank=True, help_text='URL to the issued certificate', null=True)),
                ('last_evaluation_date', models.DateTimeField(blank=True, help_text='Most recent evaluation date for this candidate (updated when evaluation is completed)', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score achieved in the evaluation (if applicable)', max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback on the evaluation', null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Link to video conference (Zoom, Google Meet, etc.)', null=True)),
                ('meeting_id', models.CharField(blank=True, help_text='Meeting ID or access code', max_length=255, null=True)),
                ('meeting_password', models.CharField(blank=True, help_text='Meeting password (if any)', max_length=255, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location for in-person evaluations', max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the evaluation was completed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the evaluation was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('candidate', models.ForeignKey(help_text='The candidate being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='candidates.candidate')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['candidate'], name='evaluations_candida_fd98ee_idx'), models.Index(fields=['status'], name='evaluations_status_f07c59_idx'), models.Index(fields=['scheduled_date'], name='evaluations_schedul_8ccbb1_idx'), models.Index(fields=['created_by'], name='evaluations_created_7efc98_idx'), models.Index(fields=['company'], name='evaluations_company_c75f3a_idx'), models.Index(fields=['evaluation_type'], name='evaluations_evaluat_076a6a_idx')],
            },
        ),
    ]
