# Generated by Django 6.0.2 on 2026-06-18 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('candidates', '0002_public_ids'),
        ('evaluations', '0003_evaluation_session_and_more'),
        ('interview_sessions', '0002_interviewsession_evaluation_tier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='readiness_override_applied',
            field=models.BooleanField(default=False, help_text='Whether a rule-based readiness override has been applied'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='readiness_override_reason',
            field=models.TextField(blank=True, help_text='Reason for readiness override, for example a failed critical question', null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='readiness_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('NOT_READY', 'Not Ready')], default='PENDING', help_text='Readiness decision after applying evaluation rules', max_length=20),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['readiness_status'], name='evaluations_readine_816a17_idx'),
        ),
    ]
