# Generated by Django 6.0.2 on 2026-07-13 11:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_public_ids'),
        ('evaluations', '0005_evaluation_certificate_enabled_and_more'),
        ('interview_sessions', '0007_merge_20260709_1624'),
        ('questions', '0003_question_schema_v12'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('role_code', models.CharField(blank=True, max_length=100)),
                ('role_name', models.CharField(blank=True, max_length=100)),
                ('evaluation_tier', models.CharField(choices=[('FULL', 'Full Evaluation'), ('SCREENING', 'Screening'), ('BOTH', 'Both')], default='FULL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scoring_rule_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scoring Rule Set',
                'verbose_name_plural': 'Scoring Rule Sets',
                'ordering': ['role_code', 'evaluation_tier', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency_code', models.CharField(max_length=150)),
                ('competency_name', models.CharField(blank=True, max_length=150)),
                ('question_code', models.CharField(blank=True, max_length=50)),
                ('question_type', models.CharField(blank=True, max_length=50)),
                ('expected_indicators', models.JSONField(blank=True, default=list)),
                ('required_indicators', models.JSONField(blank=True, default=list)),
                ('weighted_indicators', models.JSONField(blank=True, default=dict)),
                ('critical_failure_indicators', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('pass_threshold', models.DecimalField(decimal_places=2, default=7, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('scoring_method', models.CharField(choices=[('ALL_OR_NOTHING', 'All Or Nothing'), ('WEIGHTED_INDICATOR_MATCH', 'Weighted Indicator Match'), ('REQUIRED_INDICATOR_GATE', 'Required Indicator Gate'), ('CRITICAL_FAILURE_OVERRIDE', 'Critical Failure Override')], default='WEIGHTED_INDICATOR_MATCH', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('question_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoring_rules', to='questions.questiontemplate')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='evaluations.scoringruleset')),
            ],
            options={
                'verbose_name': 'Scoring Rule',
                'verbose_name_plural': 'Scoring Rules',
                'ordering': ['competency_code', 'question_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency_code', models.CharField(blank=True, max_length=150)),
                ('competency_name', models.CharField(blank=True, max_length=150)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('passed_required_indicators', models.BooleanField(default=False)),
                ('critical_failure', models.BooleanField(default=False)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('observed_indicators', models.JSONField(blank=True, default=list)),
                ('matched_indicators', models.JSONField(blank=True, default=list)),
                ('missing_indicators', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_evaluation_results', to='candidates.candidate')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_results', to='evaluations.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to='interview_sessions.sessionquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to='interview_sessions.candidateresponse')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_evaluation_results', to='interview_sessions.interviewsession')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_results', to='evaluations.scoringrule')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_results', to='evaluations.scoringruleset')),
            ],
            options={
                'verbose_name': 'Response Evaluation Result',
                'verbose_name_plural': 'Response Evaluation Results',
                'ordering': ['question__question_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency_code', models.CharField(max_length=150)),
                ('competency_name', models.CharField(blank=True, max_length=150)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pass_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('INCOMPLETE', 'Incomplete'), ('EVALUATED', 'Evaluated'), ('BELOW_THRESHOLD', 'Below Threshold'), ('MEETS_THRESHOLD', 'Meets Threshold')], default='NOT_STARTED', max_length=30)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('completed_response_count', models.PositiveIntegerField(default=0)),
                ('incomplete_response_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_evaluation_results', to='candidates.candidate')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_results', to='evaluations.evaluation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_evaluation_results', to='interview_sessions.interviewsession')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competency_results', to='evaluations.scoringruleset')),
            ],
            options={
                'verbose_name': 'Competency Evaluation Result',
                'verbose_name_plural': 'Competency Evaluation Results',
                'ordering': ['competency_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvaluationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('evaluated_response_count', models.PositiveIntegerField(default=0)),
                ('total_response_count', models.PositiveIntegerField(default=0)),
                ('incomplete_response_count', models.PositiveIntegerField(default=0)),
                ('competencies_summary', models.JSONField(blank=True, default=list)),
                ('critical_failures', models.JSONField(blank=True, default=list)),
                ('below_threshold_competencies', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_EVALUATED', 'Partially Evaluated'), ('EVALUATED', 'Evaluated'), ('EVALUATION_FAILED', 'Evaluation Failed'), ('REQUIRES_HUMAN_REVIEW', 'Requires Human Review')], default='PENDING', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_evaluation_summaries', to='candidates.candidate')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_summaries', to='evaluations.evaluation')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_summaries', to='evaluations.scoringruleset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_summaries', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Session Evaluation Summary',
                'verbose_name_plural': 'Session Evaluation Summaries',
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scoringruleset',
            index=models.Index(fields=['role_code', 'evaluation_tier', 'is_active'], name='evaluations_role_co_6805f4_idx'),
        ),
        migrations.AddIndex(
            model_name='scoringruleset',
            index=models.Index(fields=['version'], name='evaluations_version_c9eb3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoringruleset',
            constraint=models.UniqueConstraint(fields=('role_code', 'evaluation_tier', 'version'), name='unique_scoring_ruleset_role_tier_version'),
        ),
        migrations.AddIndex(
            model_name='scoringrule',
            index=models.Index(fields=['rule_set', 'competency_code'], name='evaluations_rule_se_0954b5_idx'),
        ),
        migrations.AddIndex(
            model_name='scoringrule',
            index=models.Index(fields=['question_code'], name='evaluations_questio_257d1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoringrule',
            constraint=models.UniqueConstraint(condition=models.Q(('question_template__isnull', False)), fields=('rule_set', 'question_template'), name='unique_scoring_rule_per_template'),
        ),
        migrations.AddIndex(
            model_name='responseevaluationresult',
            index=models.Index(fields=['evaluation', 'competency_code'], name='evaluations_evaluat_b929f8_idx'),
        ),
        migrations.AddIndex(
            model_name='responseevaluationresult',
            index=models.Index(fields=['session', 'scored_at'], name='evaluations_session_93bae0_idx'),
        ),
        migrations.AddConstraint(
            model_name='responseevaluationresult',
            constraint=models.UniqueConstraint(fields=('response', 'rule_set'), name='unique_response_result_per_ruleset'),
        ),
        migrations.AddIndex(
            model_name='competencyevaluationresult',
            index=models.Index(fields=['evaluation', 'status'], name='evaluations_evaluat_a75c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyevaluationresult',
            index=models.Index(fields=['session', 'competency_code'], name='evaluations_session_869a31_idx'),
        ),
        migrations.AddConstraint(
            model_name='competencyevaluationresult',
            constraint=models.UniqueConstraint(fields=('evaluation', 'rule_set', 'competency_code'), name='unique_competency_result_per_ruleset'),
        ),
        migrations.AddIndex(
            model_name='sessionevaluationsummary',
            index=models.Index(fields=['evaluation', 'status'], name='evaluations_evaluat_1fe32f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevaluationsummary',
            index=models.Index(fields=['session', 'generated_at'], name='evaluations_session_c5af63_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionevaluationsummary',
            constraint=models.UniqueConstraint(fields=('evaluation', 'rule_set'), name='unique_session_summary_per_ruleset'),
        ),
    ]
