# Generated by Django 6.0.2 on 2026-07-16 06:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_scoringruleset_scoringrule_responseevaluationresult_and_more'),
        ('interview_sessions', '0007_merge_20260709_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationReadinessDecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('readiness_indicator', models.CharField(max_length=20)),
                ('readiness_reason', models.TextField(blank=True)),
                ('override_triggered', models.BooleanField(default=False)),
                ('rule_engine_version', models.CharField(max_length=30)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_legal_record', to='evaluations.evaluation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readiness_legal_records', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Evaluation Readiness Decision Record',
                'verbose_name_plural': 'Evaluation Readiness Decision Records',
                'ordering': ['-decided_at', '-created_at'],
                'indexes': [models.Index(fields=['session', 'decided_at'], name='evaluations_session_c5b6c3_idx'), models.Index(fields=['rule_engine_version'], name='evaluations_rule_en_28c86b_idx')],
            },
        ),
    ]
