# Generated by Django 6.0.2 on 2026-07-23 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_stamp_image'),
        ('evaluations', '0008_readiness_legal_record_db_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scoringruleset',
            name='unique_scoring_ruleset_role_tier_version',
        ),
        migrations.AddField(
            model_name='scoringruleset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rule_sets', to='accounts.company'),
        ),
        migrations.AddIndex(
            model_name='scoringruleset',
            index=models.Index(fields=['company', 'role_code', 'evaluation_tier', 'is_active'], name='evaluations_company_c6b0a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoringruleset',
            constraint=models.UniqueConstraint(fields=('company', 'role_code', 'evaluation_tier', 'version'), name='unique_scoring_ruleset_company_role_tier_version'),
        ),
    ]
