# Generated by Django 6.0.2 on 2026-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='assessment_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
