# Generated by Django 6.0.2 on 2026-09-24 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_individualemployerprofile_id_document_and_more'),
        ('evaluations', '0022_alter_evaluation_readiness_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_transaction_reference', models.CharField(blank=True, max_length=255)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='evaluations.certificate')),
                ('granted_to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('granted_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate Access Grant',
                'verbose_name_plural': 'Certificate Access Grants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['certificate', 'granted_to_company'], name='evaluations_certifi_1cfa4e_idx'), models.Index(fields=['certificate', 'granted_to_user'], name='evaluations_certifi_fa3d82_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('granted_to_user__isnull', False), ('granted_to_company__isnull', False), _connector='OR'), name='cert_access_grant_has_owner')],
            },
        ),
    ]
