# Generated by Django 6.0.2 on 2026-09-29 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0024_alter_evaluation_readiness_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationReadinessCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_readiness_status', models.CharField(max_length=20)),
                ('corrected_readiness_status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('PARTIALLY_READY', 'Partially Ready'), ('NOT_READY', 'Not Ready'), ('INCOMPLETE', 'Insufficient Evidence / Incomplete')], max_length=20)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_correction', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Evaluation Readiness Correction',
                'verbose_name_plural': 'Evaluation Readiness Corrections',
                'ordering': ['-created_at'],
            },
        ),
    ]
