from django.urls import path
from .views import (
    AcceptInvitationView,
    AdminCreateB2CEmployerView,
    AdminCreateB2BEmployerView,
    AdminDashboardStatsView,
    AdminStatsView,
    AdminUserDetailView,
    AdminUserListView,
    B2CRegistrationView,
    B2BRegistrationView,
    CancelInvitationView,
    ChangePasswordView,
    CompanyProfileView,
    CreateAdminView,
    EmailVerificationView,
    EmployerDetailView,
    EmployerListView,
    ForgotPasswordView,
    InviteTeamMemberView,
    MyCompanyInfoView,
    PendingInvitationsView,
    PendingVerificationListView,
    DeleteAccountView,
    ProfileDetailView,
    ProfileDocumentUploadView,
    ProfilePictureView,
    RejectDocumentsView,
    ResendVerificationView,
    ResetPasswordView,
    TeamMemberDetailView,
    TeamMemberListView,
    TeamMemberPermissionsView,
    ValidateResetTokenView,
    VerifyDocumentsView
)

urlpatterns = [
    path('register/b2c', B2CRegistrationView.as_view(), name='register-b2c'),
    path('register/b2b', B2BRegistrationView.as_view(), name='register-b2b'),
    path('verify-email', EmailVerificationView.as_view(), name='verify-email'),
    path('resend-verification', ResendVerificationView.as_view(), name='resend-verification'),
    path('forgot-password', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password', ResetPasswordView.as_view(), name='reset-password'),
    path('validate-reset-token', ValidateResetTokenView.as_view(), name='validate-reset-token'),
    path('change-password', ChangePasswordView.as_view(), name='change-password'),
    path('me', ProfileDetailView.as_view(), name='profile-detail'),
    path('me/profile-picture', ProfilePictureView.as_view(), name='profile-picture'),
    path('me/delete', DeleteAccountView.as_view(), name='delete-account'),
    path('documents/upload', ProfileDocumentUploadView.as_view(), name='profile-document-upload'),
    path('stats', AdminStatsView.as_view(), name='admin-stats'),
    path('admin/users/create', CreateAdminView.as_view(), name='admin-create'),
    path('admin/users/<uuid:user_id>', AdminUserDetailView.as_view(), name='admin-detail'),
    path('admin/users', AdminUserListView.as_view(), name='admin-list'),
    path('admin/employers', EmployerListView.as_view(), name='employer-list'),
    path('admin/employers/create/b2c', AdminCreateB2CEmployerView.as_view(), name='admin-create-employer-b2c'),
    path('admin/employers/create/b2b', AdminCreateB2BEmployerView.as_view(), name='admin-create-employer-b2b'),
    path('admin/employers/<uuid:user_id>', EmployerDetailView.as_view(), name='employer-detail'),
    path('admin/employers/pending-verification', PendingVerificationListView.as_view(), name='pending-verification'),
    path('admin/employers/verify-documents', VerifyDocumentsView.as_view(), name='verify-documents'),
    path('admin/employers/reject-documents', RejectDocumentsView.as_view(), name='reject-documents'),
    path('admin/dashboard/stats', AdminDashboardStatsView.as_view(), name='admin--dashboard-stats'),
    path('companies/profile', CompanyProfileView.as_view(), name='company-profile'),
    path('companies/team', TeamMemberListView.as_view(), name='team-list'),
    path('companies/team/invite', InviteTeamMemberView.as_view(), name='team-invite'),
    path('companies/team/invitations', PendingInvitationsView.as_view(), name='pending-invitations'),
    path('companies/team/invitations/<int:invitation_id>/cancel', CancelInvitationView.as_view(), name='cancel-invitation'),
    path('companies/team/accept-invitation', AcceptInvitationView.as_view(), name='accept-invitation'),
    path('companies/team/members/<int:member_id>', TeamMemberDetailView.as_view(), name='team-member-detail'),
    path('companies/permissions', TeamMemberPermissionsView.as_view(), name='team-permissions'),
    path('companies/my-company', MyCompanyInfoView.as_view(), name='my-company'),

]
