# Generated by Django 6.0.2 on 2026-07-08 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_company_stamp_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_type', models.CharField(choices=[('PRIVACY_TERMS', 'Privacy Policy & Terms of Use'), ('AI_DISCLOSURE', 'AI Transparency & Disclosure Notice'), ('B2B_AGREEMENT', 'B2B Agreement'), ('DPA', 'Data Processing Agreement'), ('B2C_AGREEMENT', 'B2C Agreement'), ('CANDIDATE_CONSENT', 'Candidate Consent Form')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('OTP_SIGNATURE', 'OTP Signature')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=20)),
                ('signatory_name', models.CharField(blank=True, max_length=255)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('otp_code_hash', models.CharField(blank=True, max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('otp_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('contract_id', models.CharField(blank=True, max_length=50)),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('company', models.ForeignKey(blank=True, help_text='Set for company-scoped agreements (B2B Agreement, DPA) so the whole company is gated, not just the signing user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'agreement_type', 'status'], name='contracts_a_user_id_f1976b_idx'), models.Index(fields=['company', 'agreement_type', 'status'], name='contracts_a_company_02bc2b_idx')],
            },
        ),
    ]
