# Generated by Django 6.0.2 on 2026-07-09 12:49

import api.contracts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_public_ids'),
        ('interview_sessions', '0004_interviewsession_certificate_enabled_and_more'),
        ('payments', '0002_public_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('agreement_type', models.CharField(choices=[('privacy_terms', 'Privacy Policy & Terms of Use'), ('ai_disclosure', 'AI Transparency & Disclosure'), ('b2b_agreement', 'B2B Agreement'), ('dpa', 'Data Processing Agreement'), ('b2c_agreement', 'B2C Agreement'), ('candidate_consent', 'Candidate Consent')], db_index=True, max_length=40)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('expired', 'Expired'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('method', models.CharField(choices=[('checkbox', 'Checkbox'), ('otp_signature', 'OTP Signature')], max_length=20)),
                ('signatory_name', models.CharField(blank=True, max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('otp_reference', models.CharField(blank=True, max_length=64)),
                ('otp_code', models.CharField(blank=True, max_length=10)),
                ('otp_attempts', models.PositiveIntegerField(default=0)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('auth_checkbox_confirmed', models.BooleanField(default=False)),
                ('pdf_path', models.TextField(blank=True)),
                ('pdf_hash', models.CharField(blank=True, max_length=64)),
                ('verification_url', models.URLField(blank=True)),
                ('verbal_audio_path', models.TextField(blank=True)),
                ('company_stamp', models.FileField(blank=True, null=True, upload_to=api.contracts.models.company_stamp_upload_to)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='candidates.candidate')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseding_versions', to='contracts.agreement')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='interview_sessions.interviewsession')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='payments.subscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('reviewed', 'Reviewed'), ('checkbox_accepted', 'Checkbox Accepted'), ('otp_sent', 'OTP Sent'), ('otp_resent', 'OTP Resent'), ('otp_confirmed', 'OTP Confirmed'), ('signed', 'Signed'), ('download', 'Downloaded'), ('version_mismatch', 'Version Mismatch'), ('privacy_notice_acknowledged', 'Privacy Notice Acknowledged'), ('verbal_confirmation_recorded', 'Verbal Confirmation Recorded')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.agreement')),
            ],
            options={
                'verbose_name': 'Agreement Event',
                'verbose_name_plural': 'Agreement Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('categories_accepted', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cookie Consent',
                'verbose_name_plural': 'Cookie Consents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['user', 'agreement_type', '-created_at'], name='contracts_a_user_id_9695f2_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['candidate', 'agreement_type', '-created_at'], name='contracts_a_candida_45dba5_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['session', 'agreement_type'], name='contracts_a_session_863b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['status', 'agreement_type'], name='contracts_a_status_1651af_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['agreement_id'], name='contracts_a_agreeme_abd5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementevent',
            index=models.Index(fields=['agreement', '-created_at'], name='contracts_a_agreeme_572f79_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementevent',
            index=models.Index(fields=['event_type', '-created_at'], name='contracts_a_event_t_715e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['user', '-created_at'], name='contracts_c_user_id_94053c_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['visitor_key', '-created_at'], name='contracts_c_visitor_ec8928_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['expires_at'], name='contracts_c_expires_ab8971_idx'),
        ),
    ]
