# Generated by Django 6.0.2 on 2026-07-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='auth_checkbox_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='otp_resend_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agreement',
            name='pdf_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hex digest of the signed PDF binary.', max_length=64),
        ),
    ]
