# Generated by Django 6.0.2 on 2026-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='otp_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
