# Generated by Django 6.0.2 on 2026-09-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_agreement_auth_checkbox_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', help_text='Locale the document was reviewed/signed in — determines which language template the signed PDF is rendered from.', max_length=5),
        ),
    ]
