# Generated by Django 6.0.2 on 2026-08-25 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_roles'),
        ('payments', '0003_price_billing_type_price_evaluation_tier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='points_grant',
            field=models.PositiveIntegerField(blank=True, help_text='Points balance granted per period, spent only on optional add-ons, never on the core assessment. Null = no automated enforcement (e.g. Starter/Enterprise, per-agreement).', null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='slot_grant',
            field=models.PositiveIntegerField(blank=True, help_text='Candidate Assessment Slots granted per period (one-time for B2C, reset on each renewal for B2B). Null = no automated enforcement (e.g. Starter/Enterprise, per-agreement).', null=True),
        ),
        migrations.CreateModel(
            name='PackageBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_type', models.CharField(choices=[('SLOTS', 'Assessment Slots'), ('POINTS', 'Points')], max_length=10)),
                ('fixed_amount', models.PositiveIntegerField(help_text='The grant/reset amount from Price at the time this row was created or last reset.')),
                ('current_balance', models.PositiveIntegerField(default=0)),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_balances', to='accounts.company')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_balances', to=settings.AUTH_USER_MODEL)),
                ('source_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_balances', to='payments.payment')),
                ('source_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_balances', to='payments.subscription')),
            ],
            options={
                'verbose_name': 'Package Balance',
                'verbose_name_plural': 'Package Balances',
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('GRANT', 'Grant'), ('CONSUME', 'Consume'), ('RESET', 'Reset'), ('ADMIN_ADJUST', 'Admin Adjustment')], max_length=15)),
                ('amount', models.IntegerField(help_text='Signed: positive for GRANT/RESET, negative for CONSUME')),
                ('balance_after', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='e.g. "session:<public_id>", "addon:<addon_code>", "subscription:<stripe_subscription_id>"', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.packagebalance')),
            ],
            options={
                'verbose_name': 'Balance Transaction',
                'verbose_name_plural': 'Balance Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='packagebalance',
            index=models.Index(fields=['owner_user', 'balance_type'], name='payments_pa_owner_u_bdccac_idx'),
        ),
        migrations.AddIndex(
            model_name='packagebalance',
            index=models.Index(fields=['owner_company', 'balance_type'], name='payments_pa_owner_c_55a6f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagebalance',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', False), ('owner_company__isnull', False), _connector='OR'), name='package_balance_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='packagebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_company__isnull', False)), fields=('owner_company', 'balance_type'), name='uniq_b2b_balance_per_company_type'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['balance', '-created_at'], name='payments_ba_balance_62311c_idx'),
        ),
    ]
