# Generated by Django 6.0.2 on 2026-09-02 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_price_points_grant_price_slot_grant_packagebalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Processed Stripe Event',
                'verbose_name_plural': 'Processed Stripe Events',
                'indexes': [models.Index(fields=['stripe_event_id'], name='payments_pr_stripe__4d0c39_idx')],
            },
        ),
    ]
