# Generated by Django 6.0.2 on 2026-09-03 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_password_changed_at'),
        ('payments', '0005_processedstripeevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('GRANT', 'Grant'), ('CONSUME', 'Consume'), ('RESET', 'Reset'), ('ADMIN_ADJUST', 'Admin Adjustment'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release')], max_length=15),
        ),
        migrations.CreateModel(
            name='AddonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon_code', models.CharField(max_length=64)),
                ('points_cost', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='RESERVED', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_requests', to='accounts.company')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Add-on Request',
                'verbose_name_plural': 'Add-on Requests',
                'indexes': [models.Index(fields=['owner_user', 'status'], name='payments_ad_owner_u_ec6df4_idx'), models.Index(fields=['owner_company', 'status'], name='payments_ad_owner_c_748c47_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('owner_user__isnull', False), ('owner_company__isnull', False), _connector='OR'), name='addon_request_has_owner')],
            },
        ),
    ]
