# Generated by Django 6.0.2 on 2026-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_balancetransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('GRANT', 'Grant'), ('CONSUME', 'Consume'), ('RESET', 'Reset'), ('ADMIN_ADJUST', 'Admin Adjustment'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('REFUND', 'Refund')], max_length=15),
        ),
    ]
