# Generated by Django 6.0.2 on 2026-09-03 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_password_changed_at'),
        ('payments', '0007_alter_balancetransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal_type', models.CharField(choices=[('ENTERPRISE', 'Enterprise'), ('STARTER', 'Starter (Per Agreement)'), ('FREE_TRIAL', 'Free Trial'), ('CUSTOM_PAID_TRIAL', 'Custom Paid Trial')], max_length=20)),
                ('slot_grant', models.PositiveIntegerField(blank=True, help_text='None = still undefined, no default assumed', null=True)),
                ('points_grant', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_amount', models.DecimalField(decimal_places=2, help_text='Agreed price - 0 for a Free Trial', max_digits=10)),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('rollover_allowed', models.BooleanField(default=False, help_text='Whether unused Slots/Points carry forward on renewal - default no rollover unless the Addendum states rollover')),
                ('addendum_reference', models.CharField(blank=True, help_text='Signed Addendum / contract reference', max_length=255)),
                ('confirmation_note', models.TextField(blank=True, help_text='Lightweight internal confirmation record (e.g. for a Free Trial, no formal Addendum required)')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_records', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('price', models.OneToOneField(blank=True, help_text='Set once Ops has created the companion Stripe Product/Price for this deal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_record', to='payments.price')),
            ],
            options={
                'verbose_name': 'Deal Record',
                'verbose_name_plural': 'Deal Records',
                'indexes': [models.Index(fields=['company', 'deal_type'], name='payments_de_company_05d665_idx')],
            },
        ),
    ]
