# Generated by Django 6.0.2 on 2026-09-16 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_password_changed_at'),
        ('candidates', '0006_alter_candidate_preferred_language'),
        ('interview_sessions', '0013_normalize_session_question_skills'),
        ('payments', '0008_dealrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='RESERVED', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('balance', models.ForeignKey(blank=True, help_text='The specific PackageBalance row this Slot was drawn from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot_reservations', to='payments.packagebalance')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_reservations', to='candidates.candidate')),
                ('owner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_reservations', to='accounts.company')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_reservations', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_reservation', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Slot Reservation',
                'verbose_name_plural': 'Slot Reservations',
                'indexes': [models.Index(fields=['owner_user', 'status'], name='payments_sl_owner_u_dce1ee_idx'), models.Index(fields=['owner_company', 'status'], name='payments_sl_owner_c_f30563_idx'), models.Index(fields=['status'], name='payments_sl_status_d5726b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('owner_user__isnull', False), ('owner_company__isnull', False), _connector='OR'), name='slot_reservation_has_owner')],
            },
        ),
    ]
