# Generated by Django 6.0.2 on 2026-09-19 11:42

import api.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_slotreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='local_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=api.payments.models.invoice_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_render_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Exact context local_pdf_file was rendered from - a later regeneration (e.g. a template fix) reproduces this PDF from this stored snapshot rather than live (possibly since-changed) profile data. See api/payments/invoice_services.py.'),
        ),
    ]
