# Generated by Django 6.0.2 on 2026-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_invoice_local_pdf_file_invoice_pdf_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('GRANT', 'Grant'), ('CONSUME', 'Consume'), ('RESET', 'Reset'), ('ADMIN_ADJUST', 'Admin Adjustment'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('REFUND', 'Refund'), ('CERT_REUSE', 'Certificate Reuse')], max_length=15),
        ),
    ]
