# Generated by Django 6.0.2 on 2026-09-30 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_individualemployerprofile_id_document_and_more'),
        ('payments', '0011_alter_balancetransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal_type', models.CharField(choices=[('STARTER', 'Starter (Per Agreement)'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('requested_slot_grant', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_points_grant', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text="Requester's context/justification for this ask")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('decision_reason', models.TextField(blank=True, help_text='Required when denying; optional note when approving')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to='accounts.company')),
                ('deal_record', models.OneToOneField(blank=True, help_text='The DealRecord created when this request was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='payments.dealrecord')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package Request',
                'verbose_name_plural': 'Package Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='payments_pa_company_e390de_idx'), models.Index(fields=['status'], name='payments_pa_status_f9848f_idx')],
            },
        ),
    ]
