# Generated by Django 6.0.2 on 2026-09-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_packagerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='addendum_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='approved_points_grant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='approved_slot_grant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('ONE_TIME', 'One-Time'), ('RECURRING', 'Recurring (Monthly)')], max_length=10),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='currency',
            field=models.CharField(blank=True, default='eur', max_length=3),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='rollover_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='stripe_payment_link_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='stripe_payment_link_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text="Ad-hoc Stripe Price created for this deal's Payment Link", max_length=255),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text="Ad-hoc Stripe Product created for this deal's Payment Link", max_length=255),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='deal_record',
            field=models.OneToOneField(blank=True, help_text='The DealRecord created once payment is confirmed - null while PENDING or APPROVED-awaiting-payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='payments.dealrecord'),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved - Awaiting Payment'), ('PAID', 'Paid'), ('DENIED', 'Denied')], default='PENDING', max_length=10),
        ),
    ]
