# Generated by Django 6.0.2 on 2026-09-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_packagerequest_addendum_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='Created OPEN/unpaid at approval (with the Pay Online link as its hosted_invoice_url), updated to PAID once activate_after_payment runs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_package_request', to='payments.invoice'),
        ),
    ]
