# Generated by Django 6.0.2 on 2026-10-01 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_packagerequest_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Who manually confirmed a bank-transfer payment - null for Stripe-confirmed payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe (Pay Online)'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20),
        ),
    ]
