# Generated by Django 6.0.2 on 2026-10-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_packagerequest_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebalance',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="B2C one-time purchases only (12-month validity policy). Null = never expires - always true for B2B rows (reset every period), and for B2C rows purchased before this policy shipped (not backfilled, so existing purchases aren't retroactively revoked).", null=True),
        ),
    ]
