# Generated by Django 6.0.2 on 2026-10-09 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_packagebalance_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('target_url', models.URLField(max_length=2000)),
                ('purpose', models.CharField(blank=True, max_length=40)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Short Link',
                'verbose_name_plural': 'Payment Short Links',
                'indexes': [models.Index(fields=['target_url'], name='payments_pa_target__947f5d_idx')],
            },
        ),
    ]
