# Generated by Django 6.0.2 on 2026-10-09 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_payment_short_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerNotificationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('NO_SLOTS_AVAILABLE', 'No Assessment Slots available')], max_length=40)),
                ('owner_key', models.CharField(help_text='"COMPANY:<id>" or "USER:<id>"', max_length=64)),
            ],
            options={
                'verbose_name': 'Owner Notification Marker',
                'verbose_name_plural': 'Owner Notification Markers',
                'constraints': [models.UniqueConstraint(fields=('kind', 'owner_key'), name='unique_owner_notification_marker')],
            },
        ),
    ]
