# Generated by Django 6.0.2 on 2026-07-03 11:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview_sessions', '0005_candidateresponse_interpretation_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResponseInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('input_transcript_type', models.CharField(blank=True, max_length=30)),
                ('input_language', models.CharField(blank=True, max_length=20)),
                ('input_transcript', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, default=dict)),
                ('normalized_indicators', models.JSONField(blank=True, default=dict)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='NOT_STARTED', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('interpreted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_interpretations', to='interview_sessions.sessionquestion')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interpretation', to='interview_sessions.candidateresponse')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_interpretations', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Candidate Response Interpretation',
                'verbose_name_plural': 'Candidate Response Interpretations',
                'indexes': [models.Index(fields=['session', 'status'], name='translation_session_44e5a1_idx'), models.Index(fields=['provider', 'interpreted_at'], name='translation_provide_ee5b24_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateResponseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_language', models.CharField(blank=True, max_length=20)),
                ('target_language', models.CharField(blank=True, max_length=20)),
                ('original_transcript', models.TextField(blank=True)),
                ('translated_transcript', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='NOT_STARTED', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_translations', to='interview_sessions.sessionquestion')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation_artifact', to='interview_sessions.candidateresponse')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_translations', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Candidate Response Translation',
                'verbose_name_plural': 'Candidate Response Translations',
                'indexes': [models.Index(fields=['session', 'status'], name='translation_session_705829_idx'), models.Index(fields=['provider', 'translated_at'], name='translation_provide_1a793a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationInputArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency_code', models.CharField(blank=True, max_length=150)),
                ('expected_indicators', models.JSONField(blank=True, default=list)),
                ('observed_indicators', models.JSONField(blank=True, default=list)),
                ('missing_indicators', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('language_notes', models.JSONField(blank=True, default=dict)),
                ('source_interpretation_status', models.CharField(blank=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_input_artifacts', to='interview_sessions.sessionquestion')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_input_artifact', to='interview_sessions.candidateresponse')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_input_artifacts', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Evaluation Input Artifact',
                'verbose_name_plural': 'Evaluation Input Artifacts',
                'indexes': [models.Index(fields=['session', 'source_interpretation_status'], name='translation_session_12354a_idx'), models.Index(fields=['competency_code', 'prepared_at'], name='translation_compete_6313b2_idx')],
            },
        ),
    ]
