# Generated by Django 6.0.2 on 2026-07-06 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0006_candidateresponse_ai_processing_idempotency_key'),
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresponseinterpretation',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='candidateresponseinterpretation',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateresponseinterpretation',
            name='legal_disclaimer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateresponseinterpretation',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='candidateresponsetranslation',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='evaluationinputartifact',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='evaluationinputartifact',
            name='legal_disclaimer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationinputartifact',
            name='requires_human_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationinputartifact',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AIProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(default='PROCESS_AI', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('queue_name', models.CharField(blank=True, max_length=120)),
                ('queue_message_id', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_jobs', to='interview_sessions.sessionquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_jobs', to='interview_sessions.candidateresponse')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_jobs', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'AI Processing Job',
                'verbose_name_plural': 'AI Processing Jobs',
                'indexes': [models.Index(fields=['session', 'status'], name='translation_session_bf5172_idx'), models.Index(fields=['idempotency_key', 'status'], name='translation_idempot_47e486_idx')],
                'unique_together': {('response', 'idempotency_key')},
            },
        ),
    ]
