# Generated by Django 6.0.2 on 2026-09-18 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_candidateresponseinterpretation_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorPhraseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase_en', models.CharField(max_length=500, unique=True)),
                ('phrase_ar', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Indicator Phrase Translation',
                'verbose_name_plural': 'Indicator Phrase Translations',
            },
        ),
    ]
