# Generated by Django 6.0.2 on 2026-06-12 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=100)),
                ('language', models.CharField(default='EN', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('allow_retries', models.BooleanField(default=True)),
                ('max_retries', models.PositiveIntegerField(default=1)),
                ('enable_translation', models.BooleanField(default=False)),
                ('enable_task_module', models.BooleanField(default=False)),
                ('enable_integrity_checks', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Interview Configuration',
                'verbose_name_plural': 'Interview Configurations',
                'ordering': ['role_name', 'language'],
            },
        ),
    ]
