# Generated by Django 6.0.2 on 2026-06-17 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewconfiguration',
            options={'ordering': ['role_name', 'language', 'evaluation_tier'], 'verbose_name': 'Interview Configuration', 'verbose_name_plural': 'Interview Configurations'},
        ),
        migrations.AddField(
            model_name='interviewconfiguration',
            name='evaluation_tier',
            field=models.CharField(choices=[('FULL', 'Full Evaluation'), ('SCREENING', 'Screening')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewconfiguration',
            name='question_set_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='interviewconfiguration',
            name='role_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewconfiguration',
            name='rubric_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=100)),
                ('role_code', models.CharField(blank=True, max_length=100)),
                ('skill_tag', models.CharField(max_length=150)),
                ('scoring_category', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=6)),
                ('max_score', models.PositiveIntegerField()),
                ('scoring_type', models.CharField(max_length=50)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('rubric_version', models.CharField(blank=True, max_length=20)),
                ('question_set_version', models.CharField(blank=True, max_length=20)),
                ('evaluation_criteria', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Interview Rubric',
                'verbose_name_plural': 'Interview Rubrics',
                'ordering': ['role_name', 'skill_tag'],
                'unique_together': {('role_code', 'skill_tag', 'rubric_version')},
            },
        ),
    ]
