# Generated by Django 6.0.2 on 2026-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interviewconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewconfiguration',
            name='evaluation_tier',
            field=models.CharField(choices=[('FULL', 'Full Evaluation'), ('SCREENING', 'Screening'), ('BOTH', 'Both')], default='FULL', max_length=20),
        ),
    ]
