# Generated by Django 6.0.2 on 2026-07-02 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_allow_both_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSessionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_code', models.CharField(max_length=50, unique=True)),
                ('package_name', models.CharField(max_length=100)),
                ('audience', models.CharField(choices=[('B2C', 'B2C'), ('B2B', 'B2B'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('evaluation_tier', models.CharField(choices=[('FULL', 'Full Evaluation'), ('SCREENING', 'Screening'), ('BOTH', 'Both')], default='SCREENING', max_length=20)),
                ('min_questions', models.PositiveIntegerField(default=5)),
                ('max_questions', models.PositiveIntegerField(default=8)),
                ('default_question_count', models.PositiveIntegerField(default=5)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('task_observation_enabled', models.BooleanField(default=False)),
                ('readiness_indicator_enabled', models.BooleanField(default=False)),
                ('certificate_enabled', models.BooleanField(default=False)),
                ('basic_report_enabled', models.BooleanField(default=True)),
                ('analytics_enabled', models.BooleanField(default=False)),
                ('api_access_enabled', models.BooleanField(default=False)),
                ('video_introduction_enabled', models.BooleanField(default=False)),
                ('behavioral_indicators_enabled', models.BooleanField(default=False)),
                ('points_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_fee_display', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Package Session Config',
                'verbose_name_plural': 'Package Session Configs',
                'ordering': ['audience', 'package_name'],
            },
        ),
        migrations.CreateModel(
            name='RolePackageCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(max_length=100)),
                ('role_code', models.CharField(max_length=100)),
                ('package_code', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=100)),
                ('audience', models.CharField(choices=[('B2C', 'B2C'), ('B2B', 'B2B'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('coverage_level', models.CharField(choices=[('SCREENING', 'Screening'), ('PARTIAL', 'Partial'), ('FULL', 'Full')], default='SCREENING', max_length=20)),
                ('evaluation_tier', models.CharField(choices=[('FULL', 'Full Evaluation'), ('SCREENING', 'Screening'), ('BOTH', 'Both')], default='SCREENING', max_length=20)),
                ('readiness_indicator_enabled', models.BooleanField(default=False)),
                ('certificate_enabled', models.BooleanField(default=False)),
                ('video_introduction_enabled', models.BooleanField(default=False)),
                ('behavioral_indicators_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Role Package Coverage',
                'verbose_name_plural': 'Role Package Coverage',
                'ordering': ['role_name', 'package_name'],
                'unique_together': {('role_code', 'package_code')},
            },
        ),
    ]
