# Generated by Django 6.0.2 on 2026-06-04 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_VERIFIED', 'User Verified'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('CANDIDATE_CREATED', 'Candidate Created'), ('CANDIDATE_UPDATED', 'Candidate Updated'), ('CANDIDATE_DELETED', 'Candidate Deleted'), ('CANDIDATE_SHARED', 'Candidate Shared'), ('VIEW_MY_CANDIDATES', 'Viewed My Candidates'), ('VIEW_SHARED_CANDIDATES', 'Viewed Shared Candidates'), ('VIEW_CANDIDATE', 'Viewed Candidate Details'), ('VIEW_CANDIDATES_LIST', 'Viewed Candidates List'), ('EVALUATION_CREATED', 'Evaluation Created'), ('EVALUATION_UPDATED', 'Evaluation Updated'), ('EVALUATION_COMPLETED', 'Evaluation Completed'), ('EVALUATION_CANCELLED', 'Evaluation Cancelled'), ('EVALUATION_RESCHEDULED', 'Evaluation Rescheduled'), ('EVALUATION_DELETED', 'Evaluation Deleted'), ('VIEW_EVALUATION', 'Viewed Evaluation Details'), ('VIEW_EVALUATIONS_LIST', 'Viewed Evaluations List'), ('VIEW_UPCOMING_EVALUATIONS', 'Viewed Upcoming Evaluations'), ('VIEW_PAST_EVALUATIONS', 'Viewed Past Evaluations'), ('VIEW_MY_EVALUATIONS', 'Viewed My Evaluations'), ('VIEW_CANDIDATE_EVALUATIONS', 'Viewed Candidate Evaluations'), ('SCORE_CATEGORY_CREATED', 'Score Category Created'), ('SCORE_CATEGORY_UPDATED', 'Score Category Updated'), ('SCORE_CATEGORY_DELETED', 'Score Category Deleted'), ('SCORE_SET_CREATED', 'Score Set Created'), ('SCORE_SET_UPDATED', 'Score Set Updated'), ('SCORE_SET_DELETED', 'Score Set Deleted'), ('SCORE_SET_RECALCULATED', 'Score Set Recalculated'), ('VIEW_SCORE_SET', 'Viewed Score Set'), ('VIEW_SCORE_SETS_LIST', 'Viewed Score Sets List'), ('VIEW_SCORES_IN_SET', 'Viewed Scores in Set'), ('INDIVIDUAL_SCORE_CREATED', 'Individual Score Created'), ('INDIVIDUAL_SCORE_UPDATED', 'Individual Score Updated'), ('INDIVIDUAL_SCORE_DELETED', 'Individual Score Deleted'), ('VIEW_INDIVIDUAL_SCORE', 'Viewed Individual Score'), ('VIEW_INDIVIDUAL_SCORES_LIST', 'Viewed Individual Scores List'), ('VIEW_JOB_ROLE_AREAS', 'Viewed Job Role Areas'), ('VIEW_JOB_ROLE_AREAS_BY_ROLE', 'Viewed Job Role Areas By Role'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled'), ('SUBSCRIPTION_REACTIVATED', 'Subscription Reactivated'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('VIEW_PRICES_LIST', 'Viewed Prices List'), ('VIEW_PRICES_FOR_USER', 'Viewed Filtered Prices'), ('SYNC_PRICES_FROM_STRIPE', 'Synced Prices from Stripe'), ('CUSTOMER_RETRIEVED', 'Customer Retrieved/Created'), ('VIEW_PAYMENT_METHODS', 'Viewed Payment Methods'), ('CREATE_SETUP_INTENT', 'Created Setup Intent'), ('ATTACH_PAYMENT_METHOD', 'Attached Payment Method'), ('DETACH_PAYMENT_METHOD', 'Detached Payment Method'), ('SET_DEFAULT_PAYMENT_METHOD', 'Set Default Payment Method'), ('VIEW_SUBSCRIPTIONS_LIST', 'Viewed Subscriptions List'), ('VIEW_SUBSCRIPTION_DETAILS', 'Viewed Subscription Details'), ('SUBSCRIPTION_CREATION_FAILED', 'Subscription Creation Failed'), ('SUBSCRIPTION_PLAN_CHANGED', 'Subscription Plan Changed'), ('SUBSCRIPTION_QUANTITY_UPDATED', 'Subscription Quantity Updated'), ('SUBSCRIPTION_REACTIVATED', 'Subscription Reactivated'), ('VIEW_UPCOMING_INVOICE', 'Viewed Upcoming Invoice'), ('VIEW_SUBSCRIPTION_USAGE', 'Viewed Subscription Usage'), ('VIEW_ACTIVE_SUBSCRIPTIONS', 'Viewed Active Subscriptions'), ('VIEW_SUBSCRIPTION_INVOICES', 'Viewed Subscription Invoices'), ('ADMIN_VIEW_ALL_SUBSCRIPTIONS', 'Admin Viewed All Subscriptions'), ('ADMIN_VIEW_SUBSCRIPTION_DETAILS', 'Admin Viewed Subscription Details'), ('ADMIN_VIEW_SUBSCRIPTION_STATS', 'Admin Viewed Subscription Stats'), ('VIEW_PAYMENTS_LIST', 'Viewed Payments List'), ('VIEW_PAYMENT_DETAILS', 'Viewed Payment Details'), ('CREATE_PAYMENT_INTENT', 'Created Payment Intent'), ('VIEW_INVOICES_LIST', 'Viewed Invoices List'), ('VIEW_INVOICE_DETAILS', 'Viewed Invoice Details'), ('STRIPE_WEBHOOK_RECEIVED', 'Stripe Webhook Received'), ('STRIPE_WEBHOOK_ERROR', 'Stripe Webhook Error'), ('DEBUG_SUBSCRIPTION_DATA', 'Debug Subscription Data'), ('DEBUG_PAYMENT_DATA', 'Debug Payment Data'), ('RETRY_SUBSCRIPTION_PAYMENT', 'Retried Subscription Payment'), ('SYNC_SUBSCRIPTION_STATUS', 'Synced Subscription Status'), ('CHECK_ALL_SUBSCRIPTIONS', 'Checked All Subscriptions'), ('SYNC_ALL_SUBSCRIPTIONS', 'Synced All Subscriptions'), ('TWO_FACTOR_ENABLED', '2FA Enabled'), ('TWO_FACTOR_DISABLED', '2FA Disabled'), ('LOGIN_FAILED', 'Login Failed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('COMPANY_CREATED', 'Company Created'), ('COMPANY_UPDATED', 'Company Updated'), ('COMPANY_VERIFIED', 'Company Verified'), ('TEAM_MEMBER_INVITED', 'Team Member Invited'), ('TEAM_MEMBER_JOINED', 'Team Member Joined'), ('TEAM_MEMBER_REMOVED', 'Team Member Removed'), ('TEAM_MEMBER_UPDATED', 'Team Member Updated'), ('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_METHOD_ADDED', 'Payment Method Added'), ('PAYMENT_METHOD_REMOVED', 'Payment Method Removed'), ('SYSTEM_CONFIG_CHANGED', 'System Config Changed'), ('API_KEY_CREATED', 'API Key Created'), ('API_KEY_REVOKED', 'API Key Revoked')], db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('USER', 'User Management'), ('CANDIDATE', 'Candidate Management'), ('EVALUATION', 'Evaluation'), ('SUBSCRIPTION', 'Subscription'), ('PAYMENT', 'Payment'), ('DOCUMENT', 'Document'), ('SECURITY', 'Security'), ('COMPANY', 'Company'), ('TEAM', 'Team'), ('BILLING', 'Billing'), ('SYSTEM', 'System')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('resource_type_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.company')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['company', '-created_at'], name='audit_audit_company_832522_idx'), models.Index(fields=['category', '-created_at'], name='audit_audit_categor_529cbb_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['severity', '-created_at'], name='audit_audit_severit_49184d_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_79b1d2_idx')],
            },
        ),
    ]
