# Generated by Django 6.0.2 on 2026-06-04 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('passport_id', models.CharField(max_length=50, unique=True)),
                ('job_role', models.CharField(choices=[('NA', 'Nanny'), ('DR', 'Driver'), ('HK', 'Housekeeper'), ('EC', 'Elder Companion'), ('KA', 'Kitchen Assistant'), ('MW', 'Maintenance Worker'), ('OT', 'Other')], max_length=2)),
                ('core_skills', models.TextField(help_text='Comma-separated skills')),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('AR', 'Arabic'), ('DE', 'German'), ('ZH', 'Chinese')], default='EN', max_length=2)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=10)),
                ('passport_document', models.FileField(help_text='Upload passport/ID document', upload_to='candidates/documents/passport/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('profile_photo', models.ImageField(blank=True, help_text='Candidate profile photo', null=True, upload_to='candidates/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('last_evaluation_date', models.DateTimeField(blank=True, help_text='Most recent evaluation date for this candidate (updated when evaluation is completed)', null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_candidates', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, help_text='B2B team members who have access to this candidate', related_name='shared_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='candidates__email_188e48_idx'), models.Index(fields=['passport_id'], name='candidates__passpor_4c9d93_idx'), models.Index(fields=['status'], name='candidates__status_0f124f_idx'), models.Index(fields=['created_by'], name='candidates__created_65d526_idx'), models.Index(fields=['company'], name='candidates__company_ec53d0_idx')],
            },
        ),
    ]
