# Generated by Django 6.0.2 on 2026-07-29 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_public_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='verification_photo',
            field=models.ImageField(blank=True, help_text="AI-cropped, candidate/staff-confirmed close-up of the face from the passport document, used as the identity verification reference image instead of the full document scan. Falls back to passport_document / profile_photo when absent (e.g. candidates created before this field existed, or uploads where a face crop couldn't be produced).", null=True, upload_to='candidates/photos/verification/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
