# Generated by Django 6.0.2 on 2026-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('AM', 'Amharic'), ('OM', 'Afaan Oromo'), ('FIL', 'Filipino'), ('ZH', 'Chinese'), ('HI', 'Hindi'), ('UR', 'Urdu'), ('BN', 'Bengali'), ('TA', 'Tamil'), ('TE', 'Telugu'), ('ML', 'Malayalam'), ('PA', 'Punjabi'), ('SI', 'Sinhala'), ('ID', 'Indonesian'), ('NE', 'Nepali'), ('SW', 'Swahili'), ('VI', 'Vietnamese'), ('KM', 'Khmer'), ('MY', 'Burmese')], default='EN', max_length=3),
        ),
    ]
